# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Checkpoint Firestore CI

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'test/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/ci.yml'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Restore workspace cache
        uses: ./.github/actions/restore-workspace-cache
        with:
          cache-key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: |
          npm ci

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Restore workspace cache
        uses: ./.github/actions/restore-workspace-cache
        with:
          cache-key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Run lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Restore workspace cache
        uses: ./.github/actions/restore-workspace-cache
        with:
          cache-key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Firestore Emulator
        uses: mickfeech/firestore-emulator-action@0.0.12
        with:
          fireStoreProjectID: 'dummy-project'

      - name: Run test
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Restore workspace cache
        uses: ./.github/actions/restore-workspace-cache
        with:
          cache-key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Run build
        run: npm run build
