# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Checkpoint Firestore CI

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'test/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/ci.yml'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Restore workspace cache
        uses: ./.github/actions/restore-workspace-cache
        with:
          cache-key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: |
          npm ci

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Restore workspace cache
        uses: ./.github/actions/restore-workspace-cache
        with:
          cache-key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Run lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Restore workspace cache
        uses: ./.github/actions/restore-workspace-cache
        with:
          cache-key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      # Ensure Java is installed (See https://github.com/actions/setup-java)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Install the Firebase Emulator Suite
      - name: Start Firebase Emulator Suite
        uses: firebase-emulator-action@v1
        with:
          firebase-tools-version: '14.11.1'
          emulators: 'firestore'

      - name: Run test
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Restore workspace cache
        uses: ./.github/actions/restore-workspace-cache
        with:
          cache-key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Run build
        run: npm run build
